## YAML Template.
spring:
    datasource:
        url: jdbc:h2:file:~/userdatadb
        username: root
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                ddl-auto: update
    thymeleaf:
        cache: false
        check-template: true
        check-template-location: true
        content-type: text/html
        enabled: true
        encoding: UTF-8
        prefix: classpath:/templates/
        suffix: .html
---
