# ===============================
# = Hibernate datasource
# ===============================
spring:
    datasource:
        url: jdbc:h2:file:~/userdatadb
        username: root
        password: 

# ===============================
# = JPA configurations
# ===============================
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate.dialect: org.hibernate.dialect.H2Dialect

# ===============================
# = Email configurations
# ===============================
    mail:
        host: smtp.gmail.com
        username: m.yasir0002@gmail.com
        password: 21@October
        port: 587
        properties: 
            mail:
                transport:
                    protocol: smtp
                smtp:
                    auth: true
                    starttls:
                        enable: true
                debug: true
